// Code generated by sqlc. DO NOT EDIT.

package db

import ()

type AclPolicy struct {
	Role     string
	Resource string
	Action   string
}

type Action struct {
	ID string
}

type Resource struct {
	ID string
}

type Role struct {
	ID string
}
